###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################


###############################################################################
## Common image variables
###############################################################################
image:
  repository: websphere-liberty
  tag: latest
  pullPolicy: IfNotPresent
  license: ""

service:
  type: NodePort
  name: sample-batch-bonuspayout
  port: 9443
  targetPort: 9443

###############################################################################
## Persistence Storage
###############################################################################

## Persistence is disabled by default, set Enabled: true to use
tranlog:
  name: "tranlog"
  persistence: 
    enabled: false
    existingClaimName: ""

  ## Specify the name of the StorageClass
  ## Setting StorageClass: "" will use whatever storageClass is currently
  ## setup as the Default
    storageClassName: "" 

  ## tranlog requires a ReadWriteMany accessMode
    accessMode: "ReadWriteOnce"

  ## Tranlog requires a Persistence Storage volume size minimum of 1Gi
    size: "1Gi"

###############################################################################
## Auto scaling
###############################################################################
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
###############################################################################
## Resource constraints
###############################################################################
resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

ssl:
  enabled: true
  useClusterSSLConfiguration: true
  createClusterSSLConfiguration: false

ingress:
  enabled: true
  secureBackends: true
  rewriteTarget: "/ibm/api/batch"
  path: "/ibm/api/batch/"

###############################################################################
## MicroProfile
###############################################################################
microprofile:
  health: 
    enabled: false