-------------------------------------------------------------
-- COPYRIGHT LICENSE: This information contains sample code provided in source code form. You may copy, modify, and distribute these sample programs in any form without payment to IBM for the purposes of developing, using, marketing or distributing application programs conforming to the application programming interface for the operating platform for which the sample code is written. Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR MODIFICATIONS TO THE SAMPLE SOURCE CODE.

-- (C) Copyright IBM Corp. 2014.
-- All Rights Reserved. Licensed Materials - Property of IBM.  
-------------------------------------------------------------

-- This script creates a Derby database for batch container runtime.


CREATE TABLE JBATCH.JOBINSTANCEDATA(
  jobinstanceid BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT JBATCH.JOBINSTANCE_PK PRIMARY KEY,
  name		VARCHAR(512),
  apptag    VARCHAR(512),
  appname   VARCHAR(512),
  jobxmlname VARCHAR(512),
  submitter VARCHAR(512),
  jobxml    BLOB
);

CREATE TABLE JBATCH.EXECUTIONINSTANCEDATA(
  jobexecid BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT JBATCH.JOBEXECUTION_PK PRIMARY KEY,
  jobinstanceid BIGINT,
  createtime	TIMESTAMP,
  starttime		TIMESTAMP,
  endtime		TIMESTAMP,
  updatetime	TIMESTAMP,
  parameters	BLOB,
  batchstatus	VARCHAR(512),
  exitstatus	VARCHAR(512),
  serverId 		VARCHAR(512),
  logpath       VARCHAR(512),
  CONSTRAINT JBATCH.JOBINST_JOBEXEC_FK FOREIGN KEY (jobinstanceid) REFERENCES JBATCH.JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE
  );
  
CREATE TABLE JBATCH.STEPEXECUTIONINSTANCEDATA(
	stepexecid BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT JBATCH.STEPEXECUTION_PK PRIMARY KEY,
	jobexecid			BIGINT,
	batchstatus         VARCHAR(512),
    exitstatus			VARCHAR(512),
    stepname			VARCHAR(512),
	readcount			INTEGER,
	writecount			INTEGER,
	commitcount         INTEGER,
	rollbackcount		INTEGER,
	readskipcount		INTEGER,
	processskipcount	INTEGER,
	filtercount			INTEGER,
	writeskipcount		INTEGER,
	startTime           TIMESTAMP,
	endTime             TIMESTAMP,
	persistentData		BLOB,
	CONSTRAINT JBATCH.JOBEXEC_STEPEXEC_FK FOREIGN KEY (jobexecid) REFERENCES JBATCH.EXECUTIONINSTANCEDATA (jobexecid) ON DELETE CASCADE
); 

CREATE TABLE JBATCH.JOBSTATUS (
  jobinstanceid BIGINT NOT NULL CONSTRAINT JBATCH.JOBSTATUS_PK PRIMARY KEY,
  batchstatus  VARCHAR(512),
  exitstatus   VARCHAR(512),
  latestjobexecid BIGINT,
  currentstepid VARCHAR(512),
  restarton VARCHAR(512),
  CONSTRAINT JBATCH.JOBSTATUS_JOBINST_FK FOREIGN KEY (jobinstanceid) REFERENCES JBATCH.JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE,
  CONSTRAINT JBATCH.JOBSTATUS_JOBEXEC_FK FOREIGN KEY (latestjobexecid) REFERENCES JBATCH.EXECUTIONINSTANCEDATA (jobexecid) ON DELETE CASCADE
);

CREATE TABLE JBATCH.STEPSTATUS(
  id BIGINT NOT NULL CONSTRAINT JBATCH.STEPSTATUS_PK PRIMARY KEY,
  obj		BLOB,
  CONSTRAINT JBATCH.STEPSTATUS_STEPEXEC_FK FOREIGN KEY (id) REFERENCES JBATCH.STEPEXECUTIONINSTANCEDATA (stepexecid) ON DELETE CASCADE
);

CREATE TABLE JBATCH.CHECKPOINTDATA(
  id		VARCHAR(512) NOT NULL CONSTRAINT JBATCH.CHECKPOINTDATA_PK PRIMARY KEY,
  obj		BLOB
);

COMMIT WORK;
DISCONNECT;
  
