###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{ if .Values.ssl.createClusterSSLConfiguration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: liberty-secret-generator-deploy
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    app: {{ template "fullname" . }}  
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"  
spec:
  template:
    metadata:
      name: liberty-secret-generator-deploy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: liberty-secret-generator-deploy
        image: ibmcom/mb-tools:2.0.0
      restartPolicy: Never
{{ end }}