###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"      
spec:
{{ if or (not .Values.ingress.enabled) .Values.ingress.secureBackends }}  
  type: {{ .Values.service.type }}
{{ end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  {{ if .Values.ssl.enabled }}
    name: "{{ .Values.service.name  | trunc 57 | lower | trimSuffix "-" }}-https"
  {{ else }}
    name: {{ .Values.service.name | trunc 63 | lower | trimSuffix "-" | quote }}
  {{ end }}
  selector:
    app: {{ template "fullname" . }}
