###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

  {{ if and .Values.tranlog.persistence.enabled (not .Values.tranlog.persistence.existingClaimName) -}}
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "{{ template "fullname" . }}-{{ .Values.tranlog.name | trunc 38 | lower | trimSuffix "-" }}"
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  spec:
    {{- if .Values.tranlog.persistence.storageClassName }}
    storageClassName: {{ .Values.tranlog.persistence.storageClassName | quote }}
    {{- end }}
    accessModes:
      - {{ .Values.tranlog.persistence.accessMode | quote }}
    resources:
      requests:
        storage: {{ .Values.tranlog.persistence.size | quote }}
  {{- end }}
