
DROP TABLE "SAMPLE"."ACCOUNT";

CREATE TABLE "SAMPLE"."ACCOUNT"  (
		  "ACCTNUM" INTEGER NOT NULL, 
		  "BALANCE" INTEGER NOT NULL,		 
		  "INSTANCEID" BIGINT NOT NULL,		  
		  "ACCTCODE" VARCHAR(30) )  
		 ; 
		 
ALTER TABLE "SAMPLE"."ACCOUNT"
	ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY
		("ACCTNUM", "INSTANCEID");		 
                 
COMMIT WORK;


DISCONNECT;
